I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenes/introduction.rpy", line 148, in script
    while not maid_visited:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenes/introduction.rpy", line 148, in script
    while not maid_visited:
  File "C:\Users\False\Desktop\renpy-7.3.5-sdk\renpy\execution.py", line 59, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
cct382_vn 1.0
Sat Nov 28 18:10:47 2020
